### PR TITLE
ENG-9548: Fix acceptance tests for network access policy

### PR DESCRIPTION
**Pull request by Yowgf**
## Description of the change

This PR fixes some flaky tests for `TestAccRepositoryNetworkAccessPolicyResource`.

This PR also adds sweepers for IdP integrations and roles, and does some refactoring on the role-related tests.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review

- [x] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [x] Jira issue referenced in commit message and/or PR title

### Testing
The repository network access policy test is passing consistently.

### CODE REVIEW

**Review by VictorGFM — COMMENTED** [review]
Hi @Yowgf, I've tried to run the tests but the role_sso_group failed, but reporting a different error this time:
```
resource_cyral_role_sso_groups_test.go:44: Step 5/7 error: Error running apply: exit status 1
        
        Error: Unable to create role
        
          with cyral_role.test_role,
          on terraform_plugin_test.tf line 10, in resource "cyral_role" "test_role":
          10:   resource "cyral_role" "test_role" {
        
        error executing POST request; status code: 500; body: "{\"error\":\"Error
        while adding new group tfprov-acc-role-sso-groups-role: 409 Conflict: Top
        level group named 'tfprov-acc-role-sso-groups-role' already
        exists.\",\"code\":2,\"message\":\"Error while adding new group
        tfprov-acc-role-sso-groups-role: 409 Conflict: Top level group named
        'tfprov-acc-role-sso-groups-role' already exists.\",\"details\":[]}"
```
Could you please verify if this is not something related to these changes in the tests?

**Comment by Yowgf** [comment]
> Hi @Yowgf, I've tried to run the tests but the role_sso_group failed, but reporting a different error this time:
> Could you please verify if this is not something related to these changes in the tests?

Hi @VictorGFM . Did this happen the first time the tests ran?

**Comment by VictorGFM** [comment]
> Hi @VictorGFM . Did this happen the first time the tests ran?

Yes, it happened after I ran a `make` to run all the tests

**Comment by Yowgf** [comment]
> Yes, it happened after I ran a `make` to run all the tests
@VictorGFM Hmm that is weird. I tried here again and it worked, and from the code I can't see a reason why that would happen. Could you please try running `make sweep` and then `make` again?

**Comment by VictorGFM** [comment]
In fact there were some leftover role resources in the CP. After cleaning them with `make sweep` and running `make` again all the tests passed, thanks @Yowgf.

**Review by VictorGFM — APPROVED** [review]

**Pull request merged**
